package com.dailycodework.dreamshops.enums;

public enum OrderStatus {
  PENDING,
  PROCESSING,
  SHIPPED,
  DELIVERED,
  CANCELLED,
  RETURNED,
  REFUNDED,
  COMPLETED,
  FAILED,
  ON_HOLD,
  READY_FOR_SHIPMENT,
  SHIPPED_AND_DELIVERED,
  SHIPPED_AND_RETURNED,
  SHIPPED_AND_REFUNDED,
  SHIPPED_AND_COMPLETED,
  SHIPPED_AND_FAILED,
  SHIPPED_AND_ON_HOLD,
  SHIPPED_AND_PROCESSING,
  SHIPPED_AND_READY_FOR_SHIPMENT
}
